apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}-service
spec:
  ports:
  - name: default
    port: 8088
    targetPort: http
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}
  type: LoadBalancer
