server:
  servlet:
    context-path: /sse

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug